### ISSUE TITLE
add skipnav support

### ISSUE THREAD

**Issue by MelSumner** [ember-a11y/ember-a11y-refocus#2]
add option to turn on [skipnav links](https://webaim.org/techniques/skipnav/) as an integrated part of the message.

**Comment by dnstld** [comment]
I can help with that @MelSumner 
I'll send my thoughts ASAP
Thanks

**Comment by dnstld** [comment]
Hi @MelSumner ,

I was thinking something like this

```
<NavigationNarrator  />

// hbs
<a href={{this.skipTo}}>
  Skip to main content
</a>

// js
skipTo = '#main' || this.args.skipTo;
```

And, make the link invisible until it receives keyboard focus.

What you think?

We can allow passing the text via arg as well.

**Comment by MelSumner** [comment]
@dnstld good start! Let's think about these things: 
- add the .active class when the link is focused
- allow the user to customize the ID that should receive focus 

Also what do you think about how we should support internationalization?

**Comment by dnstld** [comment]
For internationalization I think we can allow to pass the text via arg @MelSumner 

```
<NavigationNarrator  @skipText={{t "some.translation"}} />

<a href={{this.skipTo}}>
  {{this.skipText}}
</a>

skipText = 'Skip to main content' || this.args.skipText;
```

**Comment by MelSumner** [comment]
@dnstld sounds good 👍

**Comment by dnstld** [comment]
Hi @MelSumner 
Lmk your thoughts
https://github.com/ember-a11y/ember-a11y-refocus/pull/219

**Comment by MelSumner** [comment]
@dnstld awesome, will review! 💯

**Comment by MelSumner** [comment]
Resolved!
