### ISSUE TITLE
Add renovate bot for dependency management

### ISSUE THREAD

**Issue by MelSumner** [ember-a11y/ember-a11y-refocus#207]
Add renovate bot to this addon for automated dependency management.

**Comment by dbollinger** [comment]
Initial config in PR #208.

I wonder if a good next step before adding additional repositories would be to create a common base config: https://docs.renovatebot.com/config-presets/#github-hosted-presets

**Comment by MelSumner** [comment]
@dbollinger I think that's a good idea, it would give us a good way to keep addons updated in this org.

**Comment by dbollinger** [comment]
I went ahead and merged the config last night, so we have the first round of renovate PRs this morning.  Here's an example: https://github.com/ember-a11y/ember-a11y-refocus/pull/209

**Next steps:**

- [ ] Turn off dependabot for this repo and close (or merge?) related PRs
- [ ] Create a dedicated repo in the ember-a11y group for shared renovate config
- [ ] Add renovate bot to the rest of the projects in the ember-a11y group and extend from shared config

@MelSumner -- Would you prefer to keep this issue open for these next steps, or close it and create a new one?

**Comment by MelSumner** [comment]
@dbollinger let's track it in a project, that way you can add an issue to each repo and then have PRs for that repo. 

https://github.com/orgs/ember-a11y/projects/1

**Comment by MelSumner** [comment]
@dbollinger the other thing I totally spaced on was that dependabot was already in this project. Could you remove that from this repo?
