### ISSUE TITLE
The router transition event does not fire (tested with Ember 3.24.5)

### ISSUE THREAD

**Issue by gregone** [ember-a11y/ember-a11y-refocus#302]
This addon hooks into the [`didTransition` event](https://github.com/ember-a11y/ember-a11y-refocus/blob/master/addon/components/navigation-narrator.js#L38) on the router *service*. While this event exists on routes, the router service only supports [`routeDidChange`](https://api.emberjs.com/ember/3.28/classes/RouterService/events/routeDidChange?anchor=routeDidChange&show=inherited%2Cprotected%2Cprivate%2Cdeprecated). Because of that, the event does not fire, and the message is never read by the screen reader.

I don't know if there have been any recent changes to the internals of Ember that make this work in newer versions (or older ones), but I believe the addon should be using the public API. 

Bug found with @jgwhite, @sabrinako, and @ChaiWithJai

**Comment by MelSumner** [comment]
Thank you for filing this issue, I'll look into it ASAP.

**Comment by MelSumner** [comment]
v.2.1.0 is released and should address the issue. Please try it out and let me know if you find any other issues. Thank you!
